development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://rbkulamttnwuwc:c7fa774212464bb86231599d8717e71fd44bf23358df17b375a1245a90e7e84c@ec2-54-235-193-34.compute-1.amazonaws.com:5432/d7dt83lj5aqpt
  channel_prefix: firstapp_production
